import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const robertFont = localFont({
  src: [
      {
        path: "/fonts/robert-regular.woff2",
        weight: "400"
      },
      {
        path: "/fonts/robert-medium.woff2",
        weight: "500"
      }
  ],
  variable: "--robert"
});

const zentryFont = localFont({
  src:"/fonts/zentry-regular.woff2",
  weight: "400",
  variable: "--zentry"
});

const generalFont = localFont({
  src:"/fonts/general.woff2",
  weight: "400",
  variable: "--general"
});

const circularWebFont = localFont({
  src:"/fonts/circularweb-book.woff2",
  weight: "400",
  variable: "--circular"
});


export const metadata: Metadata = {
  title: "Awwwards-Gsap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robertFont.variable} ${zentryFont.variable} ${generalFont.variable} ${circularWebFont.variable} antialiased`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
